### ISSUE TITLE
Commands doesn't work?

### ISSUE THREAD

**Issue by Thorixim** [skmedix/HideNames#7] opened 2016-12-28 16:13 UTC
Hello,
I've been using Citizens (NPC plugin) on my hamachi server, version 1.8. Now I moved to version 1.10.2, problem is that when I use F1, I see their name tags. So I searched for solution and I came here.

I tried this mod, when I logged on my server, commands didn't work.
Mods I have installed :
Pixelcam
OptiFine_1.10.2_HD_U_D4

I'm using forge-1.10.2-12.18.1.2011, because only this one is working with PixelCam, that I need.
I was wondering if problem is with forge, or I need to apply this mod somehow on server?

Edit :
http://imgur.com/a/umXrU
http://imgur.com/a/4n7SC

**Comment by skmedix** [comment] 2017-01-04 20:51
Currently mod is required both on server and client.

**Comment by skmedix** [comment] 2017-01-04 20:52
#2

**Comment by andsoon87** [comment] 2018-01-18 21:56
So what about adding support for client-only hiding of names?

**Comment by skmedix** [comment] 2018-11-29 22:55
Rewrite inc
Duplicate of #2

**Closed as completed by skmedix** 2018-11-29 22:55 UTC
